INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Diego Maradona', 'Argentina', 'Right', '1960-10-30', NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Glenn Morris','England','1983-12-20','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Ádám Nagy','Hungary','1995-06-17','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Jorge Peña','Chile','2000-07-11','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Kasper Pedersen','Denmark','1993-01-13','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Gabriel Debeljuh','Croatia','1996-09-28','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Amahl Pellegrino','Norway','1990-06-18','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Jack Bainbridge','England','1998-05-21','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Mathias Ross','Denmark','2001-01-15','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Rodrigo Hernández','Mexico','1989-02-23','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Nick Venema','Netherlands','1999-04-09','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Wayne Horlison','England','1992-02-29','Left',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Khaled Al Samiri','Saudi Arabia','1997-01-01','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Leonardo Jara','Argentina','1991-05-20','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Sam Foley','Republic of Ireland','1986-10-17','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Ben Whitfield','England','1996-02-28','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Jürgen Heil','Austria','1997-04-04','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Stefano Magnasco','Chile','1992-09-28','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Javier Osvaldo Mendoza','Argentina','1992-09-02','Left',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Paschalis Staikos','Greece','1996-02-08','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Stefan de Vrij','Netherlands','1992-02-05','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Philipp Zulechner','Austria','1990-04-12','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Santiago Vergini','Argentina','1988-08-03','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Abdou Diallo','France','1996-05-04','Left',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Matt Crooks','England','1994-01-20','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Maximiliano Urruti','Argentina','1991-02-22','Right',NOW());
INSERT INTO player (name, nationality, date_of_birth, preferred_foot, created_at) VALUES ('Johan Bertilsson','Sweden','1988-02-15','Right',NOW());